import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {createJournal} from '../desktop_bridge/owner_journal.cjs';
import {asyncQuestions,questionId,assertAsyncAnswerCurrent,planRequest} from '../desktop_bridge/plan_workflow.mjs';
import {settingsView} from '../desktop_bridge/mobile_settings.mjs';
import {desktopOperation} from '../desktop_bridge/desktop_creation.mjs';
const source=fs.readFileSync(new URL('../desktop_bridge/owner_renderer.mjs',import.meta.url),'utf8')
 .replace(/from '\.\/(.*?)'/g,(_m,name)=>`from '${new URL('../desktop_bridge/'+name,import.meta.url).href}'`)
 .replace('__CODEX_MOBILE_TEST_THREAD__','*');
function questionState(){const item={id:'async-item',type:'agentMessage',text:'',questions:[{title:'Which path?',options:['A','B']}]};return {turns:[{turnId:'turn-a',status:'inProgress',items:[item]}],requests:[]};}
const answer=(state,id='reply',status='accepted')=>({id,clientUserMessageId:id,type:'steeringUserMessage',status,input:[{type:'text',text:'<send_user_message_question_reply>\n'+JSON.stringify([{questionItemId:questionId(state.turns[0].items[0],0),question:'Which path?',answer:'A'}])+'\n</send_user_message_question_reply>'}]});
test('native async question appears, accepts freeform and disappears after desktop answer',()=>{const state=questionState();assert.equal(asyncQuestions(state).length,1);assert.deepEqual(asyncQuestions(state)[0].options.map(o=>o.label),['A','B']);state.turns[0].items.push(answer(state));assert.equal(asyncQuestions(state).length,0);});
test('dispatch guard makes first pending phone/desktop answer win, and cannot cross a turn boundary',()=>{const state=questionState(), first=answer(state,'first','pending'),second=answer(state,'second','pending');state.turns[0].items.push(first,second);assert.doesNotThrow(()=>assertAsyncAnswerCurrent(state,first.input,'first','turn-a'));assert.throws(()=>assertAsyncAnswerCurrent(state,second.input,'second','turn-a'),/already answered/);first.status='accepted';assert.throws(()=>assertAsyncAnswerCurrent(state,first.input,'first','turn-a'),/answered/);state.turns[0].status='completed';assert.throws(()=>assertAsyncAnswerCurrent(state,second.input,'second','turn-b'),/expired/);});
test('completed/failed questions expire; unknown pending answer is not blindly resubmitted',()=>{const state=questionState();state.turns[0].items.push(answer(state,'unknown','pending'));assert.equal(asyncQuestions(state).length,0);state.turns[0].items.pop();state.turns[0].status='failed';assert.equal(asyncQuestions(state).length,0);});
async function fixture(t){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mobile-plan-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));globalThis.codexMobileLabJournal=createJournal(dir,'*');
 const mod=await import('data:text/javascript,'+encodeURIComponent(source+'\n//'+randomUUID()));
 const id=randomUUID(), items=[], state={id,resumeState:'resumed',latestModel:'model-a',latestReasoningEffort:'high',latestCollaborationMode:{mode:'plan',settings:{}},mobileSettingsEpoch:'epoch',mobileSettingsRevision:1,requests:[{id:'implement-plan:turn',method:'item/plan/requestImplementation',params:{threadId:id,turnId:'turn',planContent:'Reply only DONE.'}}],turns:[{turnId:'turn',status:'completed',items:[{id:'plan',type:'plan',text:'Reply only DONE.'}]}]};
 const counter={updates:0,appends:0,held:0};
 const owner={assertThreadFollowerOwner(){},getHostId:()=> 'local',getConversation:()=>state,getConversationCwd:()=> 'C:/isolated',sendRequest:async(method)=>method==='model/list'?{data:[{model:'model-a',supportedReasoningEfforts:[{reasoningEffort:'high'}]}]}:{thread:{turns:[]},data:[]},
  updateThreadSettingsForNextTurn:async(_id,settings,condition)=>{if(condition.mobileSettingsVersion!==settingsView(state).version)return false;counter.updates++;state.latestCollaborationMode=settings.collaborationMode??state.latestCollaborationMode;state.mobileSettingsRevision++;return true;},
  removePlanImplementationRequest(){state.requests=[];},
  turnCoordinator:{loadMessages:async()=>{},readMessages:()=>items,serverQueue:{isEnabled:()=>true,load:async()=>{}},options:{wasMessageAccepted:()=>false,submissionHost:{getActiveTurnId:()=>null}},deferAutomaticTurns:()=>{counter.held++;return {[Symbol.dispose](){counter.held--;}};},mobileAppendSingle:async(_id,item)=>{counter.appends++;items.push(item);return {messageId:item.id};}}};
 return {mod,id,state,owner,items,counter,request:{operation:'implement-plan',conversationId:id,requestId:randomUUID(),messageId:randomUUID(),version:settingsView(state).version,planId:state.requests[0].id,turnId:'turn'}};
}
test('native confirmation, adoption idempotency and stable queue ID survive acknowledgment loss',async t=>{const f=await fixture(t);assert.equal(planRequest(f.state).text,'Reply only DONE.');const append=f.owner.turnCoordinator.mobileAppendSingle;f.owner.turnCoordinator.mobileAppendSingle=async(...args)=>{await append(...args);throw Error('ack lost');};assert.equal((await f.mod.settings(f.owner,f.request)).status,'uncertain');assert.equal((await f.mod.settings(f.owner,{...f.request,operation:'implementation-status'})).status,'applied');assert.equal((await f.mod.settings(f.owner,f.request)).status,'applied');assert.equal(f.counter.appends,1);assert.equal(f.counter.held,0);assert.equal(f.state.latestCollaborationMode.mode,'default');assert.match(f.items[0].text,/^PLEASE IMPLEMENT THIS PLAN:/);});
test('stale plan/settings and earlier queued discussions cannot trigger adoption',async t=>{const f=await fixture(t);assert.equal((await f.mod.settings(f.owner,{...f.request,version:'stale'})).status,'conflict');f.items.push({id:randomUUID(),text:'earlier discussion'});assert.equal((await f.mod.settings(f.owner,f.request)).status,'busy');assert.equal(f.counter.updates,0);assert.equal(f.counter.appends,0);});
test('desktop removes plan during native setting confirmation; phone cannot submit old plan',async t=>{const f=await fixture(t);const update=f.owner.updateThreadSettingsForNextTurn;f.owner.updateThreadSettingsForNextTurn=async(...args)=>{await update(...args);f.state.requests=[];return true;};assert.equal((await f.mod.settings(f.owner,f.request)).status,'conflict');assert.equal(f.counter.appends,0);});
test('mode setting preserves model/effort and uses built-in plan instructions without private fields',async t=>{const f=await fixture(t);const r=await f.mod.settings(f.owner,{conversationId:f.id,operation:'settings',requestId:randomUUID(),version:settingsView(f.state).version,model:'model-a',effort:'high',mode:'plan'});assert.equal(r.status,'applied');assert.deepEqual(f.state.latestCollaborationMode,{mode:'plan',settings:{model:'model-a',reasoning_effort:'high',developer_instructions:null}});assert.equal(r.settings.next.mode,'plan');assert(!JSON.stringify(r.settings).includes('developer_instructions'));});
test('new plan chat applies native mode before first input; ambiguous setup preserves original identity',async t=>{await fixture(t);let appends=0,modeApplied=false,created;
 const api={projects:async()=>[],send:async()=>({data:[{model:'a',isDefault:true,defaultReasoningEffort:'high',supportedReasoningEfforts:[{reasoningEffort:'high'}]}]}),defaults:async()=>({model:'a',effort:'high'}),prepareMode:async()=>{modeApplied=true;},create:async p=>{created=randomUUID();const result={status:'created',conversationId:created,firstTurn:{status:'not-requested'}};await p.onSettled(result);return {result};},append:async()=>{assert(modeApplied);appends++;}};
 const req={hostId:'local',requestId:randomUUID(),messageId:randomUUID(),target:{type:'projectless'},text:'Plan this',mode:'plan'};
 const result=await desktopOperation(api,'mobile-desktop-create',req);assert.equal(result.ready,true);assert.equal(appends,1);
 api.prepareMode=async()=>{throw Error('setup lost');};const failed={...req,requestId:randomUUID(),messageId:randomUUID()};const uncertain=await desktopOperation(api,'mobile-desktop-create',failed);assert.equal(uncertain.status,'uncertain');assert.equal(uncertain.threadId,created);assert.equal(uncertain.ready,false);assert.equal(appends,1);
});
